apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: confessions-react-frontend
  namespace: '1033224720846'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1033224720846/services/confessions-react-frontend
  uid: 051ca023-e42c-4749-920c-7e391fa93ca0
  resourceVersion: AAYI8bTCjQw
  generation: 13
  creationTimestamp: '2023-10-09T19:48:00.429642Z'
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: vukosi90@gmail.com
    serving.knative.dev/lastModifier: vukosi90@gmail.com
    run.googleapis.com/operation-id: 019aa34c-c0c5-4691-9946-d8e7ab27c898
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 58b0e63b-4d2d-4c55-b3fa-38a2e62d27b6
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1033224720846-compute@developer.gserviceaccount.com
      containers:
      - name: confessions-react-frontend-1
        image: thefirsthero/confessions-react-frontend:1.0.8
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: https://api.myconfessions.co.za
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 13
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-10-30T16:41:12.965219Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2023-10-30T16:40:53.296797Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2023-10-30T16:41:13.053452Z'
  latestReadyRevisionName: confessions-react-frontend-00013-mfn
  latestCreatedRevisionName: confessions-react-frontend-00013-mfn
  traffic:
  - revisionName: confessions-react-frontend-00013-mfn
    percent: 100
    latestRevision: true
  url: https://confessions-react-frontend-nh65oghlwa-ew.a.run.app
  address:
    url: https://confessions-react-frontend-nh65oghlwa-ew.a.run.app
